### ISSUE TITLE
useQuery not re-rendering in v0.1.0 

### ISSUE THREAD

**Issue by Ctrlmonster** [pmndrs/koota#12]
If you clone the starter template and set the `Koota` version to the latest, then no spheres can be spawned. The `useQuery` in `App.tsx` listening to `IsSphere, Position` doesn't cause a re-render. Also looks like there is a debug console.log() left (if you click remove spheres it'll print something into the console –> might be `queryFirst` or `entity.delete()` which get called in there)

**Comment by krispya** [comment]
Fixed with https://github.com/pmndrs/koota/commit/9a88dcd4a70038a738103b798bb0d4644343bb0f
