### ISSUE TITLE
useObserve trait value stays undefined when used with world

### ISSUE THREAD

**Issue by Ctrlmonster** [pmndrs/koota#13]
Hey, didn't have the time yet to make a csb for this, but putting it down here so it doesn't get lost:

I had some issues with using `useObserve` with the `world` this morning, where the trait value would stay undefined, even though I knew it to exist. Can you double check that it works in one of your apps? (Otherwise I'll make a csb later on)

**Comment by krispya** [comment]
Can you clarify if this is a type or value issue?

**Comment by Ctrlmonster** [comment]
The actual runtime value was undefined

**Comment by krispya** [comment]
Then no, my test and naive set up in an actual app both show it working. Can you reproduce it? Or tell me how to reproduce the issue?

**Comment by Ctrlmonster** [comment]
Yeah I'll see if I can reproduce it in a csb tomorrow

**Comment by Ctrlmonster** [comment]
This should reproduce it:

```jsx

function SceneContainer() {
  const world = useWorld();

  useEffect(() => {
    world.add(SomeTrait);
    return () => world.remove(SomeTrait);
  }, [world]);


  return (
    <Child />
  )
}


function Child() {
  const world = useWorld();
  const traitSnap = useObserve(world, SomeTrait);
  
  console.log(traitSnap); // <-- stays undefined

  return null;
}


```

**Comment by krispya** [comment]
Can you verify if this issue still exists with the latest version? This exact set up works with my tests and I believe v0.1.5 fixed it.

**Comment by Ctrlmonster** [comment]
Upgraded to the latest version – seems to still exist, I got the following logging `undefined` (a single time, no re-render gets triggered through the effect):

```jsx

function SceneContainer() {

  const world = useWorld();

  useLayoutEffect(() => {
    world.add(ActiveScene({current: "blockout"}));

    return () => {
      world.remove(ActiveScene);
    }
  }, [world]);

  const activeScene = useTrait(world, ActiveScene);

  console.log(activeScene);

  // ...
}

```
Let me know if you can't reproduce, I'll add you to the repo.
