### ISSUE TITLE
useQuery not updating / showing correct result

### ISSUE THREAD

**Issue by Ctrlmonster** [pmndrs/koota#7]
Pretty simple setup:

1. create a world with an entity
2. query for that entity inside `useQuery`
3. result stays empty, while manual query in effect shows entity to exist 

Managed to isolate it in this csb – open up the console to see the difference (if you're searching for it like me because of the new design – click the terminal icon on the top right):
https://codesandbox.io/p/sandbox/strange-poitras-2wl5l8?file=%2Fsrc%2FApp.js%3A14%2C35

**Comment by krispya** [comment]
Addressed by https://github.com/pmndrs/koota/pull/10
